config/routes.rb
Rails.application.routes.draw do
  resources :flats

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
  end

  def edit
  end

  def update
    @flat.update
    redirect_to flats_path
  end

  def destroy
    @flat.delete
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_navbar.html.erb
<nav class="navbar-wagon">
  <%= link_to 'Simple AirBnb', flats_path, class: "navbar-wagon-brand" %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <input class="form-control" type="text" placeholder="Search">
    <%= link_to "Search", "#", class: "navbar-wagon-item navbar-wagon-link btn" %>
    <%= link_to "Add Flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link btn" %>
</nav>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<%= render "navbar" %>

<div class= "container">
  <div class="row">
    <div class="col-12">
      <h2>All Our Flats</h2>
    </div>
  </div>
  <div class="row"></div>
    <div class="col-12">
      <p>You searched for. We found 4 on our website</p>
    </div>
  <div class="row">
    <%@flats.each do |flat|%>
    <div class="row-3">
      <div class="flat-card">
        <div class="flat-image">
        </div>
        <div class="flat-content">
          <div class="flat-title">
            <h4><%=flat.name%></h4>
          </div>
            <p><%= flat.address%></p>
          <div class="flex">
            <div class="flex">
              <i class="fas fa-user-friends"></i>
              <span><%= flat.number_of_guests%></span>
            </div>
            <div class="flex">
              <i class="fas fa-euro-sign"></i>
              <span><%= flat.price_per_night %></span>
            </div>
          </div>
        </div>
        <div class="flat-action">
          <%= link_to "More Info", flat_path(flat) %>
          <%= link_to "Edit", edit_flat_path(flat) %>
          <%= link_to 'Remove', flat_path(flat), method: :delete%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>NOTHING TO DO YET </h1>

app/views/flats/resources:flats.html.erb
<h1>Flats#resources:flats</h1>
<p>Find me in app/views/flats/resources:flats.html.erb</p>

app/views/flats/show.html.erb
<%= render "navbar" %>

<div class="map"></div>
<div class="details-container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
      <h1><%=@flat.name%></h1>
      <p><%=@flat.address%></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%=@flat.description%></p>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="fas fa-user-friends"></i>
              <span><%= @flat.number_of_guests%></span>
          </div>
          <div class="flex">
            <i class="fas fa-euro-sign"></i>
              <span><%= @flat.price_per_night %></span>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>
          <div class="flex">
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-twitter"></i>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>